version: '3.7'

services:

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - web
    networks:
      - app-network

  pg:
    image: postgres:alpine
    restart: always
    env_file:
      - ./postgres.env
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  web:
    build:
      context: .
    restart: always
    expose:
      - 8888
    env_file:
      - ./app.env
      - ./postgres.env
    volumes:
      - .:/go/src/
    depends_on:
      - pg
    networks:
      - app-network

    stdin_open: true
    tty: true


networks:
  app-network:
    name: app-network
    driver: bridge
